### PR TITLE
🐛 Fix templates for all platforms + minor fix neurips template

### LINKED ISSUE #94: TEXINPUTS does not work on Windows
I tested export templates on a windows machine and TEXINPUTS is not properly defined. It should be defined as such:

TEXINPUTS="${pluginDir}/textemplate/;"`

With a ";" rather than ":"

Will make a pr later today to fix this.

### PR DESCRIPTION
**Pull request by universvm**
closes #94 + updates the neurips template

### CODE REVIEW

**Comment by mokeyish** [comment]
Hi Leo,
I think it would be better set all platform first then overide it on win32.

```ts
  env = setPlatformValue(
    env,
    {
      'HOME': '${HOME}',
      'TEXINPUTS': '${pluginDir}/textemplate/:'
    },
    '*' // available for all platforms.
  );

  env = setPlatformValue(
    env,
    {
      'TEXINPUTS': '${pluginDir}/textemplate/;'
    },
    'win32' // available for windows only.
  );

```

**Comment by universvm** [comment]
Hey @mokeyish  , Sure sounds good. 

One question, does `win32` cover windows completely or do we need `win64` as well for 64 bits?

**Comment by mokeyish** [comment]
> Hey @mokeyish , Sure sounds good.
> 
> One question, does `win32` cover windows completely or do we need `win64` as well for 64 bits?

There is no `win64`

https://nodejs.org/api/os.html#osplatform

**Comment by universvm** [comment]
Whoops! will push the fix now

**Comment by universvm** [comment]
Should be fixed now

**Pull request merged**
