### PR TITLE
:sparkles: Support select Latex template

### PR DESCRIPTION
**Pull request by mokeyish**
图片

### CODE REVIEW

**Comment by mokeyish** [comment]
@universvm Hi Leo, I've add support for selecting Latex template.

But still need to continue to improve. Could you test it? Let's make sure that exporting to pdf with Latex template is no problem.

With this version, we can also set Environment Varables in the settings tab.

图片

Just change it to:

```env
HOME="${HOME}"
TEXINPUTS="path/to/textemplateDir:$TEXINPUTS"
```

**Comment by mokeyish** [comment]
> Hey @mokeyish ,
> 
> Good idea, I think we can set a default of TEXINPUTS like you say. Is there a way to use this plugins' folders like `${attachmentFolderPath}` ? So we could set it to:
> 
> `TEXINPUTS="${templateDir}r:$TEXINPUTS"`

The final value of Environment Variables is rendered here.

https://github.com/mokeyish/obsidian-enhancing-export/blob/92dd94b696398c95271cedaed5c92e1534927721/src/exporto0o.ts#L108-L113

So you can use 
```env
HOME="${HOME}"
TEXINPUTS="${luaDir}:$TEXINPUTS"
```
like the command template.

**Comment by universvm** [comment]
Final question to make sure I don't mess up your code. Are you asking to merge my commits from my repository into one commit with `git rebase` onto this dev branch? Or do you want me to test the dev branch as it is?

I will of course fix merge conflicts if needed.

**Comment by mokeyish** [comment]
Our goal is to provide a more convenient solution to export pdf with Latex templates.

You can change it as you want, don't worry about messing up the code (rebase + squash just hope to have a clearer commit log), my last few code commits are also inspired by your previous commits, very useful  .  The collision of ideas can make us do better.

Currently, I can think of the following two improvements:

– Support to keep the last few selected Latex template files, so that you can quickly dropdown to select templates.
– Automatically download or preset your Latex templates.

**Comment by universvm** [comment]
Hi @mokeyish ,

The problem with selecting a template in the UI you showed is that it does not take into account other files like `.sty`

If the user wanted to select their own template, they can just add the path to "Extra Arguments".

I would say: let's keep the UI as this:

244854046-868b88e8-23a8-4ca8-88fc-36967dafe0e9

This allows users to quickly change between 2 templates. I think your solution allows only 1 template at the time. And changing will also take time

If users want their custom templates they can do so in a custom command template. I don't think many people have custom templates and our templates contain 2 of the most used templates. 


Also, could we merge my repository first? If you do all of these changes it'll take me really long :/

**Comment by mokeyish** [comment]
> Hi @mokeyish ,
> 
> Could we merge my changes first? 

Yeah, you can add a Dropdown with guide here https://github.com/mokeyish/obsidian-enhancing-export/pull/80#issuecomment-1585535339

**Comment by mokeyish** [comment]
If you still have any questions, please ask me directly

**Comment by mokeyish** [comment]
#87

**Pull request closed without merging**
